const article = [
    {
        articleID: 1,
        articleTitle: 'Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit',
        articlePubDate: '2021-05-25',
        articleAuthorID: 2,
        articleContent: ' <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'    
    },
    {
        articleID: 2,
        articleTitle: 'There is no one who loves pain itself',
        articlePubDate: '2001-03-22',
        articleAuthorID: 5,
        articleContent: ' <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'
    },
    {
        articleID: 3,
        articleTitle: ' consectetur adipiscing elit. Maecenas tristi',
        articlePubDate: '2020-01-25',
        articleAuthorID: 1,
        articleContent: ' <p>In efficitur sit amet arcu in volutpat. Cras quis tristique enim. Ut bibendum commodo felis eu tincidunt. Aliquam erat volutpat. Vivamus laoreet ipsum vel orci ullamcorper condimentum. Etiam sed pulvinar tellus. Duis a sollicitudin massa. Maecenas luctus et erat ac iaculis. Nunc convallis, enim a consectetur viverra, lacus leo vestibulum nulla, in bibendum sapien quam eu neque. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Mauris dolor metus, interdum et dui in, euismod pulvinar velit. Aliquam eu turpis accumsan enim mollis rhoncus eu pharetra diam. Nam placerat quam eget malesuada sollicitudin.</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'
    },
    {
        articleID: 4,
        articleTitle: 'molestie. Praesent id semper t',
        articlePubDate: '2001-05-1',
        articleAuthorID: 5,
        articleContent: ' <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'
    },
    {
        articleID: 5,
        articleTitle: 'There is no one who loves pain itself',
        articlePubDate: '2011-03-04',
        articleAuthorID: 8,
        articleContent: ' <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'
    },
    {
        articleID: 6,
        articleTitle: 'Ut eleifend tempor iaculis. Done',
        articlePubDate: '2016-02-15',
        articleAuthorID: 4,
        articleContent: ' <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas tristique libero sit amet tortor suscipit, a posuere augue consequat. Curabitur rutrum tellus id est commodo tempor. Etiam mi turpis, elementum non libero eu, facilisis semper neque. Mauris nec imperdiet libero. Sed metus enim, aliquet sit amet porttitor nec, lacinia eu magna. Aenean finibus erat in odio viverra, sed molestie sapien molestie. Praesent id semper turpis. Nullam nec tristique lectus. Sed ac elit nec velit posuere cursus vel sit amet dui. Mauris sit amet elementum augue.</p> <p> Morbi rhoncus dignissim sem, ut pellentesque odio mollis quis. Ut eleifend tempor iaculis. Donec volutpat porta purus, sit amet pellentesque ipsum bibendum eget. Aenean lacinia eget velit sed vulputate. Curabitur vestibulum nisl sed ornare bibendum. Vestibulum congue lobortis dui, sit amet varius eros accumsan et. Sed efficitur laoreet lorem eget ornare. Sed sodales justo massa, id malesuada mauris varius id. Nunc in erat ultrices, pulvinar nibh at, auctor nibh. In hac habitasse platea dictumst. Curabitur turpis diam, placerat ac viverra nec, cursus nec urna. Aenean mi velit, vehicula eu ornare in, euismod sed risus. Donec malesuada mi ut tortor fermentum gravida. Nunc urna ligula, finibus non dapibus in, tincidunt et velit. </p>'
    },

] 